language: python
python:
- 2.7
install:
- pip install -r dev-requirements.txt
script:
- flake8 tool_aws tests
- coverage run --source=tool_aws setup.py test
- coverage report -m
after_success: coveralls
